title: Will's Garden
tagline: University and research notes by Will Liang.
description: University and research notes about machine learning, computer vision, and other interesting topics. Built and updated by Will Liang.
theme: just-the-docs

url: "https://willjhliang.github.io"
baseurl: "/public-garden"

author:
  name: Will Liang
  url: https://www.seas.upenn.edu/~wjhliang/

defaults:
  -
    scope:
      path: "notes/*"
    values:
      layout: "default"

search:
 rel_url: true

callouts:
  note:
    title: Note
    color: purple
  abstract:
    title: Abstract
    color: grey-lt
  info:
    title: Info
    color: grey-lt
  todo:
    title: Todo
    color: blue
  tip:
    title: Tip
    color: yellow
  success:
    title: Success
    color: green
  question:
    title: Question
    color: purple
  warning:
    title: Warning
    color: red
  failure:
    title: Failure
    color: red
  danger:
    title: Danger
    color: red
  bug:
    title: Bug
    color: red
  example:
    title: Example
    color: grey-lt
  quote:
    title: Quote
    color: grey-lt

aux_links:
  About Me: https://www.seas.upenn.edu/~wjhliang/

ga_tracking: G-LRN1GL29SS

plugins:
  - jekyll-seo-tag