title: Will's Garden
description: University and research notes by Will Liang.
theme: just-the-docs

url: https://willjhliang.github.io/public-garden

defaults:
  -
    scope:
      path: "notes/*"
    values:
      layout: "default"

aux_links:
  About Me: https://www.seas.upenn.edu/~wjhliang/
